### ISSUE TITLE
Connect multiple social logins in the same account

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#104]
- Allow user to connect multiple social logins in the same account. So that same review can get posted in multiple places for maximum reach and visibility.
- Test that login and linking works
- Provide settings to enable posting of reviews to different networks

**Comment by antarr** [comment]
Maybe logging in and posting reviews should be separate tickets?

**Comment by eshnil** [comment]
@antarr Yes.

This will need configuration in our Auth0 account, so I'll take this up myself. It's also a bit lower in priority since we need to fix the UI and layouts for search, reviews etc. first.

**Comment by eshnil** [comment]
@antarr Please come over to Gitter if you need any help in getting started: https://gitter.im/learn-awesome/meta

**Comment by eshnil** [comment]
Login via LinkedIn now works.

**Comment by eshnil** [comment]
Posting reviews to LinkedIn is not working.

Also, it seems GoodReads can be connected via Auth0 as a custom social connection: https://auth0.com/docs/connections/social/goodreads

**Comment by eshnil** [comment]
I have replaced the GoodReads connection via a custom oauth1 connection. On the Auth0 prompt it shows up as "Continue with OAuth1". Have raised a support request to find a solution for this.

Users can now switch on and off the automatic posting of reviews to each of their social network.
![image](https://user-images.githubusercontent.com/51651338/79045217-7cdaab00-7bf9-11ea-97bb-f2295e9cde2a.png)
