### ISSUE TITLE
Native mobile app

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#163]
A native app will be able to give better UX and take advantage of platform abilities like sharing links / notifications etc. An example Flutter app using Auth0 is available here: https://github.com/devdennysegura/flutter-auth0/tree/master/example

Here is an example of receiving share intents: https://muetsch.io/how-to-receive-sharing-intents-in-flutter.html

We can also consider building a PWA or TWA.

**Comment by eshnil** [comment]
@tabshaikh intends to build an absolutely minimal mobile app with Flutter (so it will support both Android and iOS), which pretty much does what the browser extension does. It will register as a share-intent handler, and when the OS passes a URL to this app, this will open https://learnawesome.org/items/search?q=<url> in the user's primary browser which will is a "Find or Create" flow. No actual UI is needed except an explanatory help screen.

Eventually, we do want to build a full-fledged mobile experience with all features from the Web app version. This could be built using either the GraphQL api that we provide using Hasura or Rails' JSON REST api.

**Comment by Dhiraj240** [comment]
@eshnil Should I start with initial development?,first with home screen.

**Comment by eshnil** [comment]
I made a simple Flutter app that behaves like the browser extension. Here is the repo: https://github.com/learn-awesome/mobile-app

All issues about bugs or features in the mobile app should be filed there. Closing this issue.
