### ISSUE TITLE
Merge duplicate topics

### ISSUE THREAD

**Issue by cssbubble** [learn-awesome/learn#164]
![image](https://user-images.githubusercontent.com/1849689/78367701-24475480-75e0-11ea-8b67-7e93105387ea.png)
this is an example

**Comment by eshnil** [comment]
The method `Topic.merge` does exist already: https://github.com/learn-awesome/learn/blob/master/app/models/topic.rb#L110

`User#can_merge_topic?` requires 20,000 points: https://github.com/learn-awesome/learn/blob/master/app/models/user.rb#L156

And the option to merge topics is shown on `topics/show` page: https://github.com/learn-awesome/learn/blob/master/app/views/topics/_topic.html.erb#L23

Closing this issue for now. Can create a new issue for improving the policy or feature discoverability if necessary.
