### ISSUE TITLE
"Our Ongoing Programs" is not responsive in 992x 740 resolution

### ISSUE THREAD

**Issue by kmlhsn** [learn-awesome/learn#197]
Description:
contents under "Our Ongoing Programs" section is not responsive in 992x 740 resolution
Expectation:
Contents should be responsive under "Our Ongoing Programs" section
steps:
1. Go to https://learnawesome.org/

![image](https://user-images.githubusercontent.com/32615215/92327977-4bb6b780-f07f-11ea-8282-9c082c609897.png)

**Comment by eshnil** [comment]
This is working as designed. On mobile and tablets, this is supposed to be scrollable horizontally.

Thank you so much for taking the time to report the issue though. :hugs:  Why don't you join our Slack and participate in the development discussions?
