### ISSUE TITLE
"About","Our Courses" Contents bordered box is not in the middle

### ISSUE THREAD

**Issue by kmlhsn** [learn-awesome/learn#199]
Description:
"About","Our Courses" Contents bordered box is not in the middle
Expectation:
"About","Our Courses" Contents bordered box  should be in the middle

Steps:
1. Go to https://learnawesome.org/
2. click on "About","Our Courses"

![image](https://user-images.githubusercontent.com/32615215/92328377-32633a80-f082-11ea-9f67-e95c6e7b916d.png)

**Comment by eshnil** [comment]
Adding Tailwind's `mx-auto` class on the `<article>` tag should fix it.

**Comment by eshnil** [comment]
Fixed in https://github.com/learn-awesome/learn/commit/126359771e13058acc75411421f1ae57fec69a5d

Thanks @kmlhsn for reporting the bugs. We're woefully short in contributors so I'd love to onboard you as a core developer on UI if you're interested. :smile:
