### ISSUE TITLE
Fix some licensing issues

### ISSUE THREAD

**Issue by wiki-me** [learn-awesome/learn#204]
https://github.com/learn-awesome/mobile-app

can’t find a license.

https://github.com/learn-awesome/learn/blob/master/LICENSE.md

it would be better if the file will be in a way github would recognize it and therefore display it’s license like in the Learn-awesome-react-app repository.

https://github.com/learn-awesome/book

can’t find a license.

https://github.com/learn-awesome/twinklecss

can’t find a license.

https://github.com/learn-awesome/webextension

can’t find a license.

Really cool project btw.

**Comment by nileshtrivedi** [comment]
Thanks @wiki-me 

I have added MIT license for the `mobile-app` and `webextension` repos. Other repos are not needed for LearnAwesome so I will add license at an appropriate time.
