### ISSUE TITLE
can't change nickname at all

### ISSUE THREAD

**Issue by wiki-me** [learn-awesome/learn#227]
whenever i try to change the nickname (e.g. "abkjdkfjkd"), it tells me "please match the requested format" (I can't think of any reason this format is not valid), it also does not specify any requested format on the "edit profile" page.

**Comment by eshnil** [comment]
@nileshtrivedi check this.

**Comment by dixonge** [comment]
Same - I am not even allowed to save *any* changes to my profile, even if I leave the nickname set as the default (LearnAwesome###)

**Comment by dixonge** [comment]
Looks like this may have started right after this change was made

https://github.com/learn-awesome/learn/issues/226

**Comment by nileshtrivedi** [comment]
Thanks for reporting this, folks. I was very busy lately and only got around to fix this now. The error was indeed introduced in #226 where I mistakenly used forward slashes to contain the regular expression. HTML5 input's `pattern` attribute does not work with those slashes. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
