### ISSUE TITLE
Minor fixes in Life Planner needed for public release

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learn#240]
Our life planner tool is available [here](https://learnawesome.org/life.html). It's a [standalone HTML file](https://github.com/learn-awesome/learn/blob/master/public/life.html) which saves data in user's localStorage. 

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/19304/110745201-ebd4df80-8260-11eb-8ef6-50f9c86179ee.png">

- [x] Save the slider position in localStorage

Future potential improvements:

- [x] Improve colors and typography
- [ ] Slider styling should be improved. It would be great to have the thumb blinking (see [animate-ping](https://tailwindcss.com/docs/animation#ping) from Tailwind CSS)
- [x] Support for mobile/narrow-width screens
- [ ] Rich text support in textareas
- [x] Below the "Joy" section, add a section called "Do Good". Otherwise, this tool is promoting self-indulgence and narcissism. :-)

**Comment by rajpratyush** [comment]
@nileshtrivedi I could not find the code snippets for sliders.

**Comment by REEKRAJROY** [comment]
@nileshtrivedi can you kindly mention what kind of colors and text format will be required?

**Comment by gouravmohanty7070** [comment]
Hey! Can I work on it?

**Comment by nileshtrivedi** [comment]
@gouravmohanty7070 Sure, but can you sync up with @REEKRAJROY first? He might have done some work that you can finish.

**Comment by REEKRAJROY** [comment]
@gouravmohanty7070 you can start working on the issue since I am unable to save the slider position to localStorage.

**Comment by JosephMcGreene** [comment]
@gouravmohanty7070 @gouravmohanty7070 @REEKRAJROY  This looks like a cool project! Are there still a few things to be done with this issue? And if so, can I give it a shot?

**Comment by nileshtrivedi** [comment]
@JosephMcGreene Yes, see the unchecked boxes in the issue description and feel free to raise a PR. If you'd like to chat about it, I am available in the LearnAwesome's Slack group's "meta" channel.

**Comment by nileshtrivedi** [comment]
Sure. @cactuskat, go ahead.

**Comment by sophiastr** [comment]
Hello, i want to deal with this issue.
Can i have it, please?

**Comment by nileshtrivedi** [comment]
Marking this closed after merging #268. Thanks @cssbubble for the contribution!
