### ISSUE TITLE
Provide topic search

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learn#25]
- Implement in top search field
- And/or add a search field on "Browse by topics" page

**Comment by eshnil** [comment]
Top search is topics-only for now. We should provide a prominent search on topics/index page though. See https://learn-anything.xyz/ for example.

**Comment by eshnil** [comment]
Added basic version in https://github.com/learn-awesome/learn/commit/a41056532b47cb503e5c3c8cf387283c172ebb47

**Comment by virajvchavan** [comment]
Search on /topics#index page requires exact string to be entered. (No fuzzy search).
Try searching for ruby'
