### ISSUE TITLE
Extract canonical URLs for items to avoid duplication

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learn#26]

**Comment by eshnil** [comment]
GoodReads meta tags extraction added in this commit: https://github.com/learn-awesome/learn/commit/c2f143797f89116b334cea1841883e3b2873dfc9

**Comment by eshnil** [comment]
Added some data points for YouTube, Vimeo and Wikipedia links: https://github.com/learn-awesome/learn/commit/9d3f176f9ffe34f2cada10badbd6f940b496b540
