### ISSUE TITLE
Internal server error when saving a review

### ISSUE THREAD

**Issue by glyn** [learn-awesome/learn#261]
I navigated to https://learnawesome.org/items/6fbffeb6-64a8-407c-b505-4cf5a6342bbb-montaigne-complete-essays, and clicked "want to learn" (bit of a lie, I was simply playing with the functionality of the site), then tried entering a review. When I click "save", I get an internal server error. Similarly if I click on one of the words above the review panel such as "entertaining", I also get an internal server error. (Even if I say "finished learning", the same problem occurs when entering a review.)

**Comment by nileshtrivedi** [comment]
Hi @glyn Thanks for reporting. Can you test now? I pushed one fix related to Auth0 and another related to error logging via Sentry. I just tested adding a review and it works. The UI does not give any feedback about review being saved but the data is in fact being saved. You should not run into an internal server error now.

**Comment by glyn** [comment]
Seems ok now. Thanks.
