### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by andesol** [learn-awesome/learn#274]
I tried accessing with Gitpod, which has eveything set up according to the docs, but got an error. Maybe there's something wrong in the config?

```sh
HISTFILE=/workspace/.gitpod/cmd-3 history -r; {
gp sync-await appsetupdone
} && {
bundle exec rake jobs:work
}
Required ruby-3.1.0 is not installed.
To install do: 'rvm install "ruby-3.1.0"'
gitpod /workspace/learn $  HISTFILE=/workspace/.gitpod/cmd-3 history -r; {
> gp sync-await appsetupdone
> } && {
> bundle exec rake jobs:work
> }
```

**Comment by nileshtrivedi** [comment]
Hi @andesol We have a new version of this project which is purely in Javascript. Please have a look here: https://github.com/learn-awesome/learndb

**Comment by andesol** [comment]
Cool, thanks :+1:
