### ISSUE TITLE
Browser extension for easy bookmarking or reviewing

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learn#30]
Create a Chrome/Brave/Web extension for easily adding a link and/or review. This tutorial could be a good starting point: https://developers.chrome.com/extensions/getstarted

**Comment by nileshtrivedi** [comment]
- Extension should add a button in the toolbar. Upon clicking, it should show a pop-up with a form (if the user is logged in learnawesome.org). If user is not logged in, then it should prompt the user to login.
- Before rendering the form, the extension should check whether the URL of the current tab is already added in LearnAwesome as a `Link` for an `Item`.
- If yes, then the form should show the topic and format for that item, and the reviews. The user won't need to visit learnawesome.org just to see the reviews for a link. In addition, the pop-up should show a form where user can add her own review with notes.
- If no, then the form should show fields for both item AND user's review. The latter can be collapsed by default just like on the website.

**Comment by nileshtrivedi** [comment]
This looks relevant: https://beatscodeandlife.ghost.io/building-a-bookmark-style-chrome-extension/

**Comment by eshnil** [comment]
A somewhat similar add-on for GoodReads: https://chrome.google.com/webstore/detail/add-to-goodreads/lfpebbhpojbhmeaolnjdofjeihhgncbe

**Comment by eshnil** [comment]
Started work on this task here: https://github.com/learn-awesome/webextension

**Comment by eshnil** [comment]
Published v0.2 of the extension in Chrome store: https://chrome.google.com/webstore/detail/learnawesome/mfmicnedcecjcchodnaijomibiplacie

**Comment by eshnil** [comment]
And published in Mozilla store as well: https://addons.mozilla.org/en-US/firefox/addon/learnawesome/

Closing.
