### ISSUE TITLE
Input field for topics needs better UX

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#42]
![image](https://user-images.githubusercontent.com/51651338/59933886-ee2d4f80-9467-11e9-8990-9581c1cb2b07.png)

This is clumsy. Autocomplete with multi-select (such as tags input) would be better.
![image](https://user-images.githubusercontent.com/51651338/59934094-685dd400-9468-11e9-858d-b45e2362bd07.png)

This could be used perhaps: https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

Since the # of topics isn't large, the entire list could be loaded in client-side.

**Comment by virajvchavan** [comment]
https://github.com/learn-awesome/learn/pull/56
