### ISSUE TITLE
Full design and UX audit

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#44]

**Comment by sankalp0o** [comment]
@eshnil I was meaning to do some form of an audit. Began listing down issues and possible improvements page-wise.
e.g. 
Browse by topic - https://atlasworkspace.firebaseapp.com/project/ItlALRPJvYa4UNEJyu6P/screen/YdZIGxEqCo6F0SkX8S34

**Comment by eshnil** [comment]
@sankalp0o Hey, you're more than welcome! 👏 👍  I've sent you an invite to the github org which you can accept here: https://github.com/learn-awesome

Also, do come over to https://gitter.im/learn-awesome/meta where we discuss our plans for this app.

**Comment by pareshchouhan** [comment]
Current UI to present the data is very unintuitive, It is hard to find my way around, I expect search to show me topics, but is showing content. Should we get together and discuss the UI/UX someday?
Anyone else facing the same issue?
Anyone find colour contrast odd? light purple over white makes it less contrasting, On titles darkblue text over light blue is less contrasting, we can try bold colours
Though I understand that titles are interactive element and you will need some kind of symbol to show that, but a dotted underline could do a better job, than hovering and changing colours, KISS
I would really like to know the thought process behind these colours.
