### ISSUE TITLE
Allow adding new items directly from Topic#show page

### ISSUE THREAD

**Issue by virajvchavan** [learn-awesome/learn#61]
![learnAesome1](https://user-images.githubusercontent.com/17914172/61430053-4ad83900-a946-11e9-8721-a036333bf0c0.png)
An 'Add' button in every card-header for item_type maybe.

**Comment by eshnil** [comment]
It's better to add just one link at the top instead of repeating it for every item_type. Keep in mind that we only show boxes for only those item_types which have at least one item. This is what I have implemented above.
