### ISSUE TITLE
Option to post reviews to Twitter

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#69]
- Explicitly take permission to post to Twitter timeline for this feature
- This should help with discovery
- See if a generic protocol like ActivityPub may make it possible to support more platforms

**Comment by eshnil** [comment]
Pending:
- Set up background job infra (Heroku's worker dyno?)
- Make Twitter app Read-Write so that it gets access to post tweet on user's timeline
- Test and then activate the job in `Review#after_create`

**Comment by virajvchavan** [comment]
How about using Sidekiq for background jobs?

**Comment by eshnil** [comment]
@virajvchavan Sounds good to me. Heroku provides a free worker dyno too.

**Comment by eshnil** [comment]
`Auth0Client.post_tweet(user, message)` works and is able to post messages to user's Twitter timeline. I have enabled `PostReviewToTwitterJob` in `Review#after_create`. User needs to enable it via settings first.

Currently, we are posting a link to the item. Once #71 is fixed, we will start posting link to the review instead.

**Comment by eshnil** [comment]
#71 is fixed.
