### ISSUE TITLE
Share buttons on items/topics pages

### ISSUE THREAD

**Issue by eshnil** [learn-awesome/learn#85]
Related to #78

**Comment by athityakumar** [comment]
I can take this up for Hacktoberfest.

So, do you refer the "Share to Twitter" / "Share to Facebook" kind-of share buttons in this issue? And if so, this will have to be rendered in the view of every item & topic right?

**Comment by nileshtrivedi** [comment]
@athityakumar Yes. This will be on each item and topic page. Look how GoodReads book page does it: https://www.goodreads.com/book/show/20877035-bring-up-genius

**Comment by eshnil** [comment]
Fixed in the above PR by @athityakumar. I replaced the text links with FontAwesome icons instead.
