### ISSUE TITLE
Issue with topics search

### ISSUE THREAD

**Issue by virajvchavan** [learn-awesome/learn#94]
On the page https://learnawesome.org/topics:
- The search gives results only for exact substring match, and
 does not consider white spaces and dashes.

- E.g. Searching for `machine learning` gives no results (user has to input `machine-learning` for it to show up in results)

![learnawesome-search-error](https://user-images.githubusercontent.com/17914172/65304851-4bd45380-db9f-11e9-8e59-0a63614a4523.png)

**Comment by athityakumar** [comment]
I can take this up.

Hmm, this is typically where elasticsearch would be pretty useful. Would you like to have a elastic search library (say, searchkick) to handle this? Or do you think a fuzzy js search would be better, with the back-end providing the list of all topics to front-end one-time?

**Comment by eshnil** [comment]
Fixed above. Thanks @athityakumar
